version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_beneficio
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: familia_beneficios_db
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
